import { MetricNormalizationConfig } from "./comparisonTypes";

export const METRIC_CONFIG: Record<string, MetricNormalizationConfig> = {
  performanceScore: {
    metric: "performanceScore",
    label: "Performance Score",
    unit: "",
    direction: "higher_is_better",
    poorThreshold: 50,
    weight: 5,
  },
  accessibilityScore: {
    metric: "accessibilityScore",
    label: "Accessibility Score",
    unit: "",
    direction: "higher_is_better",
    poorThreshold: 50,
    weight: 2,
  },
  seoScore: {
    metric: "seoScore",
    label: "SEO Score",
    unit: "",
    direction: "higher_is_better",
    poorThreshold: 50,
    weight: 2,
  },
  bestPracticesScore: {
    metric: "bestPracticesScore",
    label: "Best Practices Score",
    unit: "",
    direction: "higher_is_better",
    poorThreshold: 50,
    weight: 2,
  },
  lcp: {
    metric: "lcp",
    label: "Largest Contentful Paint",
    unit: "ms",
    direction: "lower_is_better",
    poorThreshold: 4000,
    weight: 5,
  },
  cls: {
    metric: "cls",
    label: "Cumulative Layout Shift",
    unit: "",
    direction: "lower_is_better",
    poorThreshold: 0.25,
    weight: 5,
  },
  inpOrTbt: {
    metric: "inpOrTbt",
    label: "INP / Total Blocking Time",
    unit: "ms",
    direction: "lower_is_better",
    poorThreshold: 500,
    weight: 4,
  },
  fcp: {
    metric: "fcp",
    label: "First Contentful Paint",
    unit: "ms",
    direction: "lower_is_better",
    poorThreshold: 3000,
    weight: 3,
  },
  ttfb: {
    metric: "ttfb",
    label: "Time to First Byte",
    unit: "ms",
    direction: "lower_is_better",
    poorThreshold: 800,
    weight: 3,
  },
};
